spring.application.name=AUTH-SERVICE

server.port=8760


spring.datasource.url=jdbc:postgresql://localhost:5432/authService
spring.datasource.username=postgres
spring.datasource.password=Venkat@2004
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret=TWljcm9zZXJ2aWNlc1R3aXR0ZXJDbG9uZUF1dGhTZXJ2aWNlU3VwZXJTZWNyZXRLZXkyMDI2UHJvZHVjdGlvbg==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=2592000000