spring.application.name=social-service

server.port = 8084
spring.redis.host=localhost
spring.redis.port=6379

spring.datasource.url=jdbc:postgresql://localhost:5432/socialService
spring.datasource.username=postgres
spring.datasource.password=Venkat@2004
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
resilience4j.circuitbreaker.instances.tweetService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.tweetService.slidingWindowSize=10
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true