server:
  port: 8089

jwt:
  secret: TWljcm9zZXJ2aWNlc1R3aXR0ZXJDbG9uZUF1dGhTZXJ2aWNlU3VwZXJTZWNyZXRLZXkyMDI2UHJvZHVjdGlvbg==

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # AUTH SERVICE
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**,/api/admin/**,/api/internal/**,/api/test/**

            # TWEET SERVICE
            - id: tweet-service
              uri: lb://TWEET-SERVICE
              predicates:
                - Path=/api/tweets/**

            # SOCIAL SERVICE
            - id: social-service
              uri: lb://SOCIAL-SERVICE
              predicates:
                - Path=/api/bookmarks/**,/api/feed/**,/api/follows/**,/api/likes/**,/api/replies/**,/api/retweets/**,/api/profile/**,/social

            # NOTIFICATION SERVICE
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notification/**

            # NOTIFICATION WEBSOCKET
            - id: notification-websocket
              uri: lb:ws://NOTIFICATION-SERVICE
              predicates:
                - Path=/ws/notifications**

            # MEDIA SERVICE
            - id: media-service
              uri: lb://MEDIA-SERVICE
              predicates:
                - Path=/media/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE